require "user.ntree"
require "user.lualine"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.autopairs"
require "user.transparent"
require "user.ts-autotag"
require "user.neogit"
require "user.diffview"
require "user.which-key"
require "user.bufferline"

require "user.plugins"
require "user.keymaps"
require "user.options"
