require "user.options"
require "user.plugins"
require "user.ntree"
require "user.lualine"
require "user.keymaps"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.autopairs"
require "user.transparent"

