vim.cmd([[set bg=light]])

vim.cmd([[color PaperColor]])

vim.cmd([[hi TablineFill guibg=#eeeeee]])
vim.cmd([[hi TablineSel guifg=#e0af68 guibg=#eeeeee]])
vim.cmd([[hi Tabline guifg=#6874A9 guibg=#eeeeee]])
vim.cmd([[hi Comment guifg=#6874A9]])
vim.cmd([[hi LineNr guifg=#6874A9]])
vim.cmd([[hi Substitute guibg=#ffaaaa guifg=#666666]])
vim.cmd([[hi Folded guibg=#dddddd]])

vim.cmd([[hi DiagnosticVirtualTextWarn guifg=#937244 guibg=#eeeeee]])
vim.cmd([[hi DiagnosticVirtualTextError guifg=#942C3E guibg=#eeeeee]])
vim.cmd([[hi DiagnosticVirtualTextInfo guifg=#0db9d7 guibg=#eeeeee]])
vim.cmd([[hi DiagnosticVirtualTextHint guifg=#2B7568 guibg=#eeeeee]])
vim.cmd([[hi DiagError guifg=#C52C47 guibg=#eeeeee]])
vim.cmd([[hi DiagWarn guifg=#e0af68  guibg=#eeeeee]])
vim.cmd([[hi DiagHint guifg=#2B7568  guibg=#eeeeee]])
vim.cmd([[hi DiagInfo guifg=#0db9d7  guibg=#eeeeee]])
